version: "3.8"
services:
  contabilidad-api:
    image: contabilidad-api:latest
    container_name: contabilidad_api
    restart: always
    network_mode: "host"
    security_opt:
      - apparmor:unconfined
    environment:
      - NODE_ENV=production
    volumes:
      - ./app.js:/app/app.js
      - ./cotizaciones.js:/app/cotizaciones.js
      - ./informes.js:/app/informes.js
      - ./notas.js:/app/notas.js
      - ./storage.js:/app/storage.js
      - ./index.html:/app/index.html
      - ./server.js:/app/server.js
      - ./src:/app/src
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - /home/administrador/.config/rclone:/home/administrador/.config/rclone
      - /home/administrador/.config/rclone:/root/.config/rclone
